# Form implementation generated from reading ui file 'SpecControl.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from matplotlib.figure import Figure
from matplotlib.backends.backend_qtagg import FigureCanvasQTAgg
from PyQt6 import QtCore, QtGui, QtWidgets
import sys
import matplotlib
import time
matplotlib.use('QtAgg')


class MplCanvas(FigureCanvasQTAgg):

    def __init__(self, parent=None, width=5, height=4, dpi=100):
        fig = Figure(figsize=(width, height), dpi=dpi)
        self.axes = fig.add_subplot(111)
        super(MplCanvas, self).__init__(fig)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        # Create the main window
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(1070, 600)

        # Create the central widget
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        # Create layout for connection widgets
        self.verticalLayoutWidget = QtWidgets.QWidget(
            parent=self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 181, 291))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")

        # Create the COM port label
        self.ArdCOMPortLabel = QtWidgets.QLabel(
            parent=self.verticalLayoutWidget)
        self.ArdCOMPortLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ArdCOMPortLabel.setObjectName("ArdCOMPortLabel")
        self.verticalLayout.addWidget(self.ArdCOMPortLabel)

        # Create the COM port spin box
        self.COMPortSpinBox = QtWidgets.QSpinBox(
            parent=self.verticalLayoutWidget)
        self.COMPortSpinBox.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight |
                                         QtCore.Qt.AlignmentFlag.AlignTrailing | QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.COMPortSpinBox.setObjectName("COMPortSpinBox")
        self.COMPortSpinBox.setMinimum(0)
        self.COMPortSpinBox.setMaximum(255)
        self.verticalLayout.addWidget(self.COMPortSpinBox)

        # Create the warning label with red text
        self.ArdCOMWarningLabel = QtWidgets.QLabel(
            parent=self.verticalLayoutWidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active,
                         QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive,
                         QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled,
                         QtGui.QPalette.ColorRole.WindowText, brush)
        self.ArdCOMWarningLabel.setPalette(palette)
        self.ArdCOMWarningLabel.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignHCenter | QtCore.Qt.AlignmentFlag.AlignTop)
        self.ArdCOMWarningLabel.setObjectName("ArdCOMWarningLabel")
        self.verticalLayout.addWidget(self.ArdCOMWarningLabel)

        # Create the connection buttons
        self.ManualConnectButton = QtWidgets.QPushButton(
            parent=self.verticalLayoutWidget)
        self.ManualConnectButton.setMinimumSize(QtCore.QSize(0, 68))
        self.ManualConnectButton.setObjectName("ManualConnectButton")
        self.verticalLayout.addWidget(self.ManualConnectButton)
        self.AutoConnectButton = QtWidgets.QPushButton(
            parent=self.verticalLayoutWidget)
        self.AutoConnectButton.setMinimumSize(QtCore.QSize(0, 68))
        self.AutoConnectButton.setObjectName("AutoConnectButton")
        self.verticalLayout.addWidget(self.AutoConnectButton)
        self.TTLConnectButton = QtWidgets.QPushButton(
            parent=self.verticalLayoutWidget)
        self.TTLConnectButton.setMinimumSize(QtCore.QSize(0, 68))
        self.TTLConnectButton.setObjectName("TTLConnectButton")
        self.verticalLayout.addWidget(self.TTLConnectButton)

        # Create the text browser
        self.textBrowser = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(200, 10, 261, 291))
        self.textBrowser.setObjectName("textBrowser")

        # Create a line dividing the arduino and motor controls
        self.line = QtWidgets.QFrame(parent=self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 300, 1041, 20))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")

        # Create the valve control widgets
        self.gridLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(470, 10, 181, 291))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.Valve2Button = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.Valve2Button.setMinimumSize(QtCore.QSize(0, 50))
        self.Valve2Button.setObjectName("Valve2Button")
        self.gridLayout.addWidget(self.Valve2Button, 1, 1, 1, 1)
        self.Valve1Button = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.Valve1Button.setMinimumSize(QtCore.QSize(0, 50))
        self.Valve1Button.setObjectName("Valve1Button")
        self.gridLayout.addWidget(self.Valve1Button, 1, 0, 1, 1)
        self.ValveLabel = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.ValveLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ValveLabel.setObjectName("ValveLabel")
        self.gridLayout.addWidget(self.ValveLabel, 0, 0, 1, 2)
        self.Valve7Button = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.Valve7Button.setMinimumSize(QtCore.QSize(0, 50))
        self.Valve7Button.setObjectName("Valve7Button")
        self.gridLayout.addWidget(self.Valve7Button, 4, 0, 1, 1)
        self.Valve6Button = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.Valve6Button.setMinimumSize(QtCore.QSize(0, 50))
        self.Valve6Button.setObjectName("Valve6Button")
        self.gridLayout.addWidget(self.Valve6Button, 3, 1, 1, 1)
        self.Valve3Button = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.Valve3Button.setMinimumSize(QtCore.QSize(0, 50))
        self.Valve3Button.setObjectName("Valve3Button")
        self.gridLayout.addWidget(self.Valve3Button, 2, 0, 1, 1)
        self.Valve5Button = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.Valve5Button.setMinimumSize(QtCore.QSize(0, 50))
        self.Valve5Button.setObjectName("Valve5Button")
        self.gridLayout.addWidget(self.Valve5Button, 3, 0, 1, 1)
        self.Valve4Button = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.Valve4Button.setMinimumSize(QtCore.QSize(0, 50))
        self.Valve4Button.setObjectName("Valve4Button")
        self.gridLayout.addWidget(self.Valve4Button, 2, 1, 1, 1)
        self.Valve8Button = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.Valve8Button.setMinimumSize(QtCore.QSize(0, 50))
        self.Valve8Button.setObjectName("Valve8Button")
        self.gridLayout.addWidget(self.Valve8Button, 4, 1, 1, 1)

        # Create the save path widgets
        self.SetSavePathButton = QtWidgets.QPushButton(
            parent=self.gridLayoutWidget)
        self.SetSavePathButton.setObjectName("SetSavePathButton")
        self.gridLayout.addWidget(self.SetSavePathButton, 5, 1, 1, 1)
        self.SavePathEdit = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.SavePathEdit.setDragEnabled(False)
        self.SavePathEdit.setObjectName("SavePathEdit")
        self.gridLayout.addWidget(self.SavePathEdit, 7, 0, 1, 2)
        self.SaveButton = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.SaveButton.setObjectName("SaveButton")
        self.gridLayout.addWidget(self.SaveButton, 5, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        # Create the status bar
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        # Create the graph widgets
        self.figure = Figure()
        self.sc = MplCanvas(self, width=5, height=4, dpi=100)
        self.graphWidget = QtWidgets.QWidget(
            parent=self.centralwidget)
        self.graphWidget.setGeometry(QtCore.QRect(660, 10, 231, 291))
        self.graphWidget.setObjectName("graphWidget")
        self.graphLayout = QtWidgets.QVBoxLayout(self.graphWidget)
        self.graphLayout.setContentsMargins(0, 0, 0, 0)
        self.graphLayout.setObjectName("graphLayout")
        self.graphLayout.addWidget(self.sc)

        # Create the graph control widgets
        self.graphControlWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.graphControlWidget.setGeometry(QtCore.QRect(900, 10, 161, 291))
        self.graphControlWidget.setObjectName("graphControlWidget")
        self.graphControlLayout = QtWidgets.QGridLayout(
            self.graphControlWidget)
        self.graphControlLayout.setContentsMargins(0, 0, 0, 0)
        self.graphControlLayout.setObjectName("graphControlLayout")
        self.startReadingButton = QtWidgets.QPushButton(
            parent=self.graphControlWidget)
        self.startReadingButton.setObjectName("startReadingButton")
        self.startReadingButton.setMinimumSize(QtCore.QSize(0, 100))
        self.graphControlLayout.addWidget(self.startReadingButton, 0, 0, 1, 2)
        self.graphLabel1 = QtWidgets.QLabel(parent=self.graphControlWidget)
        self.graphLabel1.setObjectName("graphLabel1")
        self.graphControlLayout.addWidget(self.graphLabel1, 1, 0, 1, 1, alignment=QtCore.Qt.AlignmentFlag.AlignRight)
        self.graphLabel2 = QtWidgets.QLabel(parent=self.graphControlWidget)
        self.graphLabel2.setObjectName("graphLabel2")
        self.graphControlLayout.addWidget(self.graphLabel2, 2, 0, 1, 1, alignment=QtCore.Qt.AlignmentFlag.AlignRight)
        self.graphLabel3 = QtWidgets.QLabel(parent=self.graphControlWidget)
        self.graphLabel3.setObjectName("graphLabel3")
        self.graphControlLayout.addWidget(self.graphLabel3, 3, 0, 1, 1, alignment=QtCore.Qt.AlignmentFlag.AlignRight)
        self.graphLabel4 = QtWidgets.QLabel(parent=self.graphControlWidget)
        self.graphLabel4.setObjectName("graphLabel4")
        self.graphControlLayout.addWidget(self.graphLabel4, 4, 0, 1, 1, alignment=QtCore.Qt.AlignmentFlag.AlignRight)
        
        # Create the quick bubble widgets
        self.quickBubbleButton = QtWidgets.QPushButton(
            parent=self.graphControlWidget)
        self.quickBubbleButton.setObjectName("quickBubbleButton")
        self.quickBubbleButton.setMinimumSize(QtCore.QSize(0, 50))
        self.graphControlLayout.addWidget(self.quickBubbleButton, 5, 0, 1, 2)
        self.bubbleTimeLabel = QtWidgets.QLabel(parent=self.graphControlWidget)
        self.bubbleTimeLabel.setObjectName("bubbleTimeLabel")
        self.graphControlLayout.addWidget(self.bubbleTimeLabel, 6, 0, 1, 1)
        self.bubbleTimeEdit = QtWidgets.QLineEdit(
            parent=self.graphControlWidget)
        self.bubbleTimeEdit.setObjectName("bubbleTimeEdit")
        self.graphControlLayout.addWidget(self.bubbleTimeEdit, 6, 1, 1, 1)

        # Create the graph control checkboxes
        self.P1Toggle = QtWidgets.QCheckBox(parent=self.graphControlWidget)
        self.P1Toggle.setObjectName("P1Toggle")
        self.graphControlLayout.addWidget(self.P1Toggle, 1, 1, 1, 1)
        self.P2Toggle = QtWidgets.QCheckBox(parent=self.graphControlWidget)
        self.P2Toggle.setObjectName("P2Toggle")
        self.graphControlLayout.addWidget(self.P2Toggle, 2, 1, 1, 1)
        self.P3Toggle = QtWidgets.QCheckBox(parent=self.graphControlWidget)
        self.P3Toggle.setObjectName("P3Toggle")
        self.graphControlLayout.addWidget(self.P3Toggle, 3, 1, 1, 1)
        self.P4Toggle = QtWidgets.QCheckBox(parent=self.graphControlWidget)
        self.P4Toggle.setObjectName("P4Toggle")
        self.graphControlLayout.addWidget(self.P4Toggle, 4, 1, 1, 1)

        # Create the motor control widgets - cols 1 & 2
        self.motorControlWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.motorControlWidget.setGeometry(QtCore.QRect(10, 330, 1051, 261))
        self.motorControlWidget.setObjectName("motorControlWidget")
        self.motorControlLayout = QtWidgets.QGridLayout(self.motorControlWidget)
        self.motorControlLayout.setContentsMargins(0, 0, 0, 0)
        self.motorControlLayout.setObjectName("motorControlLayout")
        self.motorControlLabel = QtWidgets.QLabel(parent=self.motorControlWidget)
        self.motorControlLabel.setObjectName("motorControlLabel")
        self.motorControlLabel.setMinimumSize(QtCore.QSize(150, 30))
        self.motorControlLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.motorControlLayout.addWidget(self.motorControlLabel, 0, 0, 1, 1)
        self.motorPortSpinBox = QtWidgets.QSpinBox(parent=self.motorControlWidget)
        self.motorPortSpinBox.setObjectName("motorPortSpinBox")
        self.motorPortSpinBox.setMinimumSize(QtCore.QSize(150, 30))
        self.motorPortSpinBox.setMinimum(0)
        self.motorPortSpinBox.setMaximum(255)
        self.motorControlLayout.addWidget(self.motorPortSpinBox, 0, 1, 1, 1)
        self.motorConnectButton = QtWidgets.QPushButton(parent=self.motorControlWidget)
        self.motorConnectButton.setObjectName("motorConnectButton")
        self.motorConnectButton.setMinimumSize(QtCore.QSize(300, 30))
        self.motorControlLayout.addWidget(self.motorConnectButton, 1, 0, 1, 2)
        self.calibrateButton = QtWidgets.QPushButton(parent=self.motorControlWidget)
        self.calibrateButton.setObjectName("calibrateButton")
        self.calibrateButton.setMinimumSize(QtCore.QSize(300, 30))
        self.motorControlLayout.addWidget(self.calibrateButton, 2, 0, 1, 2)
        self.motorPositionLabel = QtWidgets.QLabel(parent=self.motorControlWidget)
        self.motorPositionLabel.setObjectName("motorPositionLabel")
        self.motorPositionLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.motorPositionLabel.setMinimumSize(QtCore.QSize(150, 30))
        self.motorControlLayout.addWidget(self.motorPositionLabel, 3, 0, 1, 1)
        self.motorPositionSpinBox = QtWidgets.QSpinBox(parent=self.motorControlWidget)
        self.motorPositionSpinBox.setObjectName("motorPositionSpinBox")
        self.motorPositionSpinBox.setMinimum(0)
        self.motorPositionSpinBox.setMaximum(1000)
        self.motorPositionSpinBox.setMinimumSize(QtCore.QSize(150, 30))
        self.motorControlLayout.addWidget(self.motorPositionSpinBox, 3, 1, 1, 1)
        self.motorPositionButton = QtWidgets.QPushButton(parent=self.motorControlWidget)
        self.motorPositionButton.setObjectName("motorPositionButton")
        self.motorPositionButton.setMinimumSize(QtCore.QSize(300, 30))
        self.motorControlLayout.addWidget(self.motorPositionButton, 4, 0, 1, 2)
        self.motorErrorLabel = QtWidgets.QLabel(parent=self.motorControlWidget)
        self.motorErrorLabel.setObjectName("motorErrorLabel")
        self.motorErrorLabel.setMinimumSize(QtCore.QSize(300, 30))       
        self.motorErrorLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.motorErrorLabel.setPalette(palette)
        self.motorControlLayout.addWidget(self.motorErrorLabel, 5, 0, 1, 2)

        # Create the motor control widgets - cols 3 & 4
        self.motorReadPositionLabel = QtWidgets.QLabel(parent=self.motorControlWidget)
        self.motorReadPositionLabel.setObjectName("motorReadPositionLabel")
        self.motorReadPositionLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.motorReadPositionLabel.setMinimumSize(QtCore.QSize(150, 30))
        self.motorControlLayout.addWidget(self.motorReadPositionLabel, 0, 3, 1, 1)
        self.motorReadEdit = QtWidgets.QLineEdit(parent=self.motorControlWidget)
        self.motorReadEdit.setObjectName("motorReadEdit")
        self.motorReadEdit.setReadOnly(True)
        self.motorReadEdit.setMinimumSize(QtCore.QSize(150, 30))
        self.motorControlLayout.addWidget(self.motorReadEdit, 0, 4, 1, 1)
        self.motorReadPositionButton = QtWidgets.QPushButton(parent=self.motorControlWidget)
        self.motorReadPositionButton.setObjectName("motorReadPositionButton")
        self.motorReadPositionButton.setMinimumSize(QtCore.QSize(300, 30))
        self.motorControlLayout.addWidget(self.motorReadPositionButton, 1, 3, 1, 2)
        self.motorStopButton = QtWidgets.QPushButton(parent=self.motorControlWidget)
        self.motorStopButton.setObjectName("motorStopButton")
        self.motorStopButton.setMinimumSize(QtCore.QSize(300, 170))
        self.motorStopButton.setFont(QtGui.QFont("Arial", 36))
        self.motorControlLayout.addWidget(self.motorStopButton, 2, 3, 4, 2)

        # Create the motor control widgets - cols 5 & 6
        self.motorToTopButton = QtWidgets.QPushButton(parent=self.motorControlWidget)
        self.motorToTopButton.setObjectName("motorToTopButton")
        self.motorToTopButton.setMinimumSize(QtCore.QSize(300, 30))
        self.motorControlLayout.addWidget(self.motorToTopButton, 0, 5, 1, 2)
        self.motorSlowAscentButton = QtWidgets.QPushButton(parent=self.motorControlWidget)
        self.motorSlowAscentButton.setObjectName("motorSlowAscentButton")
        self.motorSlowAscentButton.setMinimumSize(QtCore.QSize(300, 30))
        self.motorControlLayout.addWidget(self.motorSlowAscentButton, 1, 5, 1, 2)
        self.motorMoveShortUpButton = QtWidgets.QPushButton(parent=self.motorControlWidget)
        self.motorMoveShortUpButton.setObjectName("motorMoveShortUpButton")
        self.motorMoveShortUpButton.setMinimumSize(QtCore.QSize(300, 30))
        self.motorControlLayout.addWidget(self.motorMoveShortUpButton, 2, 5, 1, 2)
        self.motorMoveShortDownButton = QtWidgets.QPushButton(parent=self.motorControlWidget)
        self.motorMoveShortDownButton.setObjectName("motorMoveShortDownButton")
        self.motorMoveShortDownButton.setMinimumSize(QtCore.QSize(300, 30))
        self.motorControlLayout.addWidget(self.motorMoveShortDownButton, 3, 5, 1, 2)
        self.motorSlowDescentButton = QtWidgets.QPushButton(parent=self.motorControlWidget)
        self.motorSlowDescentButton.setObjectName("motorSlowDescentButton")
        self.motorSlowDescentButton.setMinimumSize(QtCore.QSize(300, 30))
        self.motorControlLayout.addWidget(self.motorSlowDescentButton, 4, 5, 1, 2)
        self.motorToBottomButton = QtWidgets.QPushButton(parent=self.motorControlWidget)
        self.motorToBottomButton.setObjectName("motorToBottomButton")
        self.motorToBottomButton.setMinimumSize(QtCore.QSize(300, 30))
        self.motorControlLayout.addWidget(self.motorToBottomButton, 5, 5, 1, 2)

        # Add the text to the widgets
        self.retranslateUi(MainWindow)
        # Connect the buttons to the functions
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Spectrometer GUI"))
        self.ArdCOMPortLabel.setText(_translate("MainWindow", "Arduino COM Port"))
        self.ArdCOMWarningLabel.setText(_translate("MainWindow", "arduino not connected"))
        self.ManualConnectButton.setText(
            _translate("MainWindow", "Manual Connect"))
        self.AutoConnectButton.setText(
            _translate("MainWindow", "Auto Connect"))
        self.TTLConnectButton.setText(_translate("MainWindow", "TTL Connect"))
        self.Valve2Button.setText(_translate("MainWindow", "Inlet"))
        self.Valve1Button.setText(_translate("MainWindow", "Gas Switch"))
        self.ValveLabel.setText(_translate("MainWindow", "Valves"))
        self.Valve7Button.setText(_translate("MainWindow", "V7"))
        self.Valve6Button.setText(_translate("MainWindow", "V6"))
        self.Valve3Button.setText(_translate("MainWindow", "Outlet"))
        self.Valve5Button.setText(_translate("MainWindow", "Short"))
        self.Valve4Button.setText(_translate("MainWindow", "Vent"))
        self.Valve8Button.setText(_translate("MainWindow", "V8"))
        self.SetSavePathButton.setText(
            _translate("MainWindow", "Set Save Path"))
        self.SaveButton.setText(_translate("MainWindow", "Save"))
        self.startReadingButton.setText(
            _translate("MainWindow", "Start Reading"))
        self.graphLabel1.setText(_translate("MainWindow", "Toggle P1"))
        self.graphLabel2.setText(_translate("MainWindow", "Toggle P2"))
        self.graphLabel3.setText(_translate("MainWindow", "Toggle P3"))
        self.graphLabel4.setText(_translate("MainWindow", "Toggle P4"))
        self.quickBubbleButton.setText(
            _translate("MainWindow", "Quick Bubble"))
        self.bubbleTimeLabel.setText(
            _translate("MainWindow", "Bubble Time (ms)"))
        self.bubbleTimeEdit.setText(_translate("MainWindow", "100"))
        self.SavePathEdit.setText(_translate(
            "MainWindow", "C:\\NMR Results\\" + time.strftime("%m-%d-%H-%M") + ".csv"))
        self.motorControlLabel.setText(_translate("MainWindow", "Motor COM Port"))
        self.motorConnectButton.setText(
            _translate("MainWindow", "Connect Motor"))
        self.calibrateButton.setText(_translate("MainWindow", "Calibrate Motor"))
        self.motorPositionLabel.setText(_translate("MainWindow", "Target Position (mm)"))
        self.motorPositionButton.setText(
            _translate("MainWindow", "Move to Position"))
        self.motorErrorLabel.setText(_translate("MainWindow", "motor not connected"))
        self.motorReadPositionLabel.setText(_translate("MainWindow", "Motor Pos (mm)"))
        self.motorReadPositionButton.setText(_translate("MainWindow", "Get Position"))
        self.motorStopButton.setText(_translate("MainWindow", "Stop Motor"))

        self.motorToTopButton.setText(_translate("MainWindow", "Move to Top"))
        self.motorSlowAscentButton.setText(_translate("MainWindow", "Slow Ascent"))
        self.motorMoveShortUpButton.setText(_translate("MainWindow", "Move 5mm Up"))
        self.motorMoveShortDownButton.setText(_translate("MainWindow", "Move 5mm Down"))
        self.motorSlowDescentButton.setText(_translate("MainWindow", "Slow Descent"))
        self.motorToBottomButton.setText(_translate("MainWindow", "Move to Bottom"))


class MainWindow(QtWidgets.QMainWindow, Ui_MainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)

        # Example plot
        self.plot()

    def plot(self):
        self.sc.axes.plot([0, 1, 2, 3], [10, 1, 20, 3])
        self.sc.draw()


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    window = MainWindow()
    window.show()
    window.plot()
    sys.exit(app.exec())
