# Form implementation generated from reading ui file 'SpecControl.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from matplotlib.figure import Figure
from matplotlib.backends.backend_qtagg import FigureCanvasQTAgg
from PyQt6 import QtCore, QtGui, QtWidgets
import sys
import matplotlib
import time
matplotlib.use('QtAgg')


class MplCanvas(FigureCanvasQTAgg):

    def __init__(self, parent=None, width=5, height=4, dpi=100):
        fig = Figure(figsize=(width, height), dpi=dpi)
        self.axes = fig.add_subplot(111)
        super(MplCanvas, self).__init__(fig)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        # Create the main window
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1070, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(
            parent=self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 181, 291))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ArdCOMPortLabel = QtWidgets.QLabel(
            parent=self.verticalLayoutWidget)
        self.ArdCOMPortLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ArdCOMPortLabel.setObjectName("ArdCOMPortLabel")
        self.verticalLayout.addWidget(self.ArdCOMPortLabel)
        self.COMPortSpinBox = QtWidgets.QSpinBox(
            parent=self.verticalLayoutWidget)
        self.COMPortSpinBox.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight |
                                         QtCore.Qt.AlignmentFlag.AlignTrailing | QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.COMPortSpinBox.setObjectName("COMPortSpinBox")
        self.COMPortSpinBox.setMinimum(0)
        self.COMPortSpinBox.setMaximum(255)
        self.verticalLayout.addWidget(self.COMPortSpinBox)
        self.ArdCOMWarningLabel = QtWidgets.QLabel(
            parent=self.verticalLayoutWidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active,
                         QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive,
                         QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled,
                         QtGui.QPalette.ColorRole.WindowText, brush)
        self.ArdCOMWarningLabel.setPalette(palette)
        self.ArdCOMWarningLabel.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignHCenter | QtCore.Qt.AlignmentFlag.AlignTop)
        self.ArdCOMWarningLabel.setObjectName("ArdCOMWarningLabel")
        self.verticalLayout.addWidget(self.ArdCOMWarningLabel)
        self.ManualConnectButton = QtWidgets.QPushButton(
            parent=self.verticalLayoutWidget)
        self.ManualConnectButton.setMinimumSize(QtCore.QSize(0, 68))
        self.ManualConnectButton.setObjectName("ManualConnectButton")
        self.verticalLayout.addWidget(self.ManualConnectButton)
        self.AutoConnectButton = QtWidgets.QPushButton(
            parent=self.verticalLayoutWidget)
        self.AutoConnectButton.setMinimumSize(QtCore.QSize(0, 68))
        self.AutoConnectButton.setObjectName("AutoConnectButton")
        self.verticalLayout.addWidget(self.AutoConnectButton)
        self.TTLConnectButton = QtWidgets.QPushButton(
            parent=self.verticalLayoutWidget)
        self.TTLConnectButton.setMinimumSize(QtCore.QSize(0, 68))
        self.TTLConnectButton.setObjectName("TTLConnectButton")
        self.verticalLayout.addWidget(self.TTLConnectButton)
        self.textBrowser = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(200, 10, 261, 291))
        self.textBrowser.setObjectName("textBrowser")
        self.line = QtWidgets.QFrame(parent=self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 300, 1041, 20))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(470, 10, 181, 291))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.Valve2Button = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.Valve2Button.setMinimumSize(QtCore.QSize(0, 50))
        self.Valve2Button.setObjectName("Valve2Button")
        self.gridLayout.addWidget(self.Valve2Button, 1, 1, 1, 1)
        self.Valve1Button = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.Valve1Button.setMinimumSize(QtCore.QSize(0, 50))
        self.Valve1Button.setObjectName("Valve1Button")
        self.gridLayout.addWidget(self.Valve1Button, 1, 0, 1, 1)
        self.ValveLabel = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.ValveLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ValveLabel.setObjectName("ValveLabel")
        self.gridLayout.addWidget(self.ValveLabel, 0, 0, 1, 2)
        self.Valve7Button = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.Valve7Button.setMinimumSize(QtCore.QSize(0, 50))
        self.Valve7Button.setObjectName("Valve7Button")
        self.gridLayout.addWidget(self.Valve7Button, 4, 0, 1, 1)
        self.Valve6Button = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.Valve6Button.setMinimumSize(QtCore.QSize(0, 50))
        self.Valve6Button.setObjectName("Valve6Button")
        self.gridLayout.addWidget(self.Valve6Button, 3, 1, 1, 1)
        self.Valve3Button = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.Valve3Button.setMinimumSize(QtCore.QSize(0, 50))
        self.Valve3Button.setObjectName("Valve3Button")
        self.gridLayout.addWidget(self.Valve3Button, 2, 0, 1, 1)
        self.Valve5Button = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.Valve5Button.setMinimumSize(QtCore.QSize(0, 50))
        self.Valve5Button.setObjectName("Valve5Button")
        self.gridLayout.addWidget(self.Valve5Button, 3, 0, 1, 1)
        self.Valve4Button = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.Valve4Button.setMinimumSize(QtCore.QSize(0, 50))
        self.Valve4Button.setObjectName("Valve4Button")
        self.gridLayout.addWidget(self.Valve4Button, 2, 1, 1, 1)
        self.Valve8Button = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.Valve8Button.setMinimumSize(QtCore.QSize(0, 50))
        self.Valve8Button.setObjectName("Valve8Button")
        self.gridLayout.addWidget(self.Valve8Button, 4, 1, 1, 1)
        self.SetSavePathButton = QtWidgets.QPushButton(
            parent=self.gridLayoutWidget)
        self.SetSavePathButton.setObjectName("SetSavePathButton")
        self.gridLayout.addWidget(self.SetSavePathButton, 5, 1, 1, 1)
        self.SavePathEdit = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.SavePathEdit.setDragEnabled(False)
        self.SavePathEdit.setObjectName("SavePathEdit")
        self.gridLayout.addWidget(self.SavePathEdit, 7, 0, 1, 2)
        self.SaveButton = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.SaveButton.setObjectName("SaveButton")
        self.gridLayout.addWidget(self.SaveButton, 5, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.figure = Figure()
        self.sc = MplCanvas(self, width=5, height=4, dpi=100)
        self.graphWidget = QtWidgets.QWidget(
            parent=self.centralwidget)
        self.graphWidget.setGeometry(QtCore.QRect(660, 10, 231, 291))
        self.graphWidget.setObjectName("graphWidget")
        self.graphLayout = QtWidgets.QVBoxLayout(self.graphWidget)
        self.graphLayout.setContentsMargins(0, 0, 0, 0)
        self.graphLayout.setObjectName("graphLayout")
        self.graphLayout.addWidget(self.sc)

        self.graphControlWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.graphControlWidget.setGeometry(QtCore.QRect(900, 10, 161, 291))
        self.graphControlWidget.setObjectName("graphControlWidget")
        self.graphControlLayout = QtWidgets.QGridLayout(
            self.graphControlWidget)
        self.graphControlLayout.setContentsMargins(0, 0, 0, 0)
        self.graphControlLayout.setObjectName("graphControlLayout")
        self.startReadingButton = QtWidgets.QPushButton(
            parent=self.graphControlWidget)
        self.startReadingButton.setObjectName("startReadingButton")
        self.graphControlLayout.addWidget(self.startReadingButton, 0, 0, 1, 2)
        self.graphLabel1 = QtWidgets.QLabel(parent=self.graphControlWidget)
        self.graphLabel1.setObjectName("graphLabel1")
        self.graphControlLayout.addWidget(self.graphLabel1, 1, 0, 1, 1)
        self.graphLabel2 = QtWidgets.QLabel(parent=self.graphControlWidget)
        self.graphLabel2.setObjectName("graphLabel2")
        self.graphControlLayout.addWidget(self.graphLabel2, 2, 0, 1, 1)
        self.graphLabel3 = QtWidgets.QLabel(parent=self.graphControlWidget)
        self.graphLabel3.setObjectName("graphLabel3")
        self.graphControlLayout.addWidget(self.graphLabel3, 3, 0, 1, 1)
        self.graphLabel4 = QtWidgets.QLabel(parent=self.graphControlWidget)
        self.graphLabel4.setObjectName("graphLabel4")
        self.graphControlLayout.addWidget(self.graphLabel4, 4, 0, 1, 1)
        self.quickBubbleButton = QtWidgets.QPushButton(
            parent=self.graphControlWidget)
        self.quickBubbleButton.setObjectName("quickBubbleButton")
        self.graphControlLayout.addWidget(self.quickBubbleButton, 5, 0, 1, 2)
        self.bubbleTimeLabel = QtWidgets.QLabel(parent=self.graphControlWidget)
        self.bubbleTimeLabel.setObjectName("bubbleTimeLabel")
        self.graphControlLayout.addWidget(self.bubbleTimeLabel, 6, 0, 1, 1)
        self.bubbleTimeEdit = QtWidgets.QLineEdit(
            parent=self.graphControlWidget)
        self.bubbleTimeEdit.setObjectName("bubbleTimeEdit")
        self.graphControlLayout.addWidget(self.bubbleTimeEdit, 6, 1, 1, 1)
        self.bubbleTimeEdit.setText("100")
        self.P1Toggle = QtWidgets.QCheckBox(parent=self.graphControlWidget)
        self.P1Toggle.setObjectName("P1Toggle")
        self.graphControlLayout.addWidget(self.P1Toggle, 1, 1, 1, 1)
        self.P2Toggle = QtWidgets.QCheckBox(parent=self.graphControlWidget)
        self.P2Toggle.setObjectName("P2Toggle")
        self.graphControlLayout.addWidget(self.P2Toggle, 2, 1, 1, 1)
        self.P3Toggle = QtWidgets.QCheckBox(parent=self.graphControlWidget)
        self.P3Toggle.setObjectName("P3Toggle")
        self.graphControlLayout.addWidget(self.P3Toggle, 3, 1, 1, 1)
        self.P4Toggle = QtWidgets.QCheckBox(parent=self.graphControlWidget)
        self.P4Toggle.setObjectName("P4Toggle")
        self.graphControlLayout.addWidget(self.P4Toggle, 4, 1, 1, 1)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Spectrometer GUI"))
        self.ArdCOMPortLabel.setText(_translate("MainWindow", "COM Port"))
        self.ArdCOMWarningLabel.setText(_translate("MainWindow", "TextLabel"))
        self.ManualConnectButton.setText(
            _translate("MainWindow", "Manual Connect"))
        self.AutoConnectButton.setText(
            _translate("MainWindow", "Auto Connect"))
        self.TTLConnectButton.setText(_translate("MainWindow", "TTL Connect"))
        self.Valve2Button.setText(_translate("MainWindow", "In"))
        self.Valve1Button.setText(_translate("MainWindow", "OpH"))
        self.ValveLabel.setText(_translate("MainWindow", "Valves"))
        self.Valve7Button.setText(_translate("MainWindow", "V7"))
        self.Valve6Button.setText(_translate("MainWindow", "V6"))
        self.Valve3Button.setText(_translate("MainWindow", "Out"))
        self.Valve5Button.setText(_translate("MainWindow", "Short"))
        self.Valve4Button.setText(_translate("MainWindow", "NN"))
        self.Valve8Button.setText(_translate("MainWindow", "V8"))
        self.SetSavePathButton.setText(
            _translate("MainWindow", "Set Save Path"))
        self.SaveButton.setText(_translate("MainWindow", "Save"))
        self.startReadingButton.setText(
            _translate("MainWindow", "Start Reading"))
        self.graphLabel1.setText(_translate("MainWindow", "Toggle P1"))
        self.graphLabel2.setText(_translate("MainWindow", "Toggle P2"))
        self.graphLabel3.setText(_translate("MainWindow", "Toggle P3"))
        self.graphLabel4.setText(_translate("MainWindow", "Toggle P4"))
        self.quickBubbleButton.setText(
            _translate("MainWindow", "Quick Bubble"))
        self.bubbleTimeLabel.setText(
            _translate("MainWindow", "Bubble Time (ms)"))
        self.SavePathEdit.setText(_translate(
            "MainWindow", "C:\\NMR Results\\" + time.strftime("%y-%m-%d") + ".csv"))


class MainWindow(QtWidgets.QMainWindow, Ui_MainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)

        # Example plot
        self.plot()

    def plot(self):
        self.sc.axes.plot([0, 1, 2, 3], [10, 1, 20, 3])
        self.sc.draw()


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    window = MainWindow()
    window.show()
    window.plot()
    sys.exit(app.exec())
